### ISSUE TITLE
Eleventy (11ty) Ethereal - Yarn dev fails on Mac, does not create dist directories

### ISSUE THREAD

**Issue by davidrhoden** [app-generator/eleventy-html5up-ethereal#2]
Just installed on Mac High Sierra. On command `yarn dev`, we get a warning:

`warning package.json: License should be a valid SPDX license expression`

Then the build fails. The command that fails is:
`> npm-run-all clean cp:js cp:fonts cp:img styles:dev scripts:dev eleventy:default --parallel eleventy:watch serve --print-label`

The debug log says:
```
12 info lifecycle eleventy-html5up-ethereal@0.0.1~dev: Failed to exec dev script
13 verbose stack Error: eleventy-html5up-ethereal@0.0.1 dev: `npm-run-all clean cp:js cp:fonts cp:img styles:dev scripts:dev eleventy:default --parallel eleventy:watch serve --print-label`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid eleventy-html5up-ethereal@0.0.1
15 verbose cwd /Users/davidrhoden/Sites/eleventy-html5up-ethereal
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v10.15.3
19 verbose npm  v6.13.7
20 error code ELIFECYCLE
21 error errno 1
22 error eleventy-html5up-ethereal@0.0.1 dev: `npm-run-all clean cp:js cp:fonts cp:img styles:dev scripts:dev eleventy:default --parallel eleventy:watch serve --print-label`
22 error Exit status 1
23 error Failed at the eleventy-html5up-ethereal@0.0.1 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Additionally, this command seems to not work:
``` > cpx src/assets/js/*.* ./dist/assets/js/```
The `dist` directory is not created.

**Comment by app-generator** [comment]
[cpx](https://www.npmjs.com/package/cpx) (the tool used to copy assets) works on Windows-based system, on Linux distros (Debian, RHEL, Mac) does nothing. 
Patch: the starter will use [npc](https://www.npmjs.com/package/npc) for assets management.

**Comment by app-generator** [comment]
Patch [commit](https://github.com/app-generator/eleventy-html5up-ethereal/commit/cd5b8e2485a842798dbda23df08fcdae7e734754) 
Patch info:
- [cpx](https://www.npmjs.com/package/cpx) replaced with [npc](https://www.npmjs.com/package/npc) - CPX was unstable on Linux distros
- Added [mkdirp](https://www.npmjs.com/package/mkdirp) for dirs management

Tested on: 
- Windows 10 x64 - Node v12.16
- Ubuntu 16.04 LTS x64 - Node v12.16

I will close the issue
